name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0.4
          elixir-version: 1.10.4

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

  warnings:
    name: Compile warnings check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0.4
          elixir-version: 1.10.4

      - name: Install dependencies
        run: mix deps.get

      - name: Check compilation warnings
        run: mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0.4
          elixir-version: 1.10.4

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Run tests
        run: |
          mix test
